name: exam_flutter
description: Application météo mondiale avec Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: ^5.4.0
  retrofit: ^4.1.0

  # State Management
  flutter_riverpod: ^2.5.1

  # Carte (OpenStreetMap - 100% gratuit, sans clé API)
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Animations
  lottie: ^3.1.0
  animated_text_kit: ^4.2.2

  # Serialisation
  json_annotation: ^4.9.0

  # Utilitaires
  geolocator: ^11.0.0

  # Google Fonts
  google_fonts: ^6.2.1

  # Icônes
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.8
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/animations/
